{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "C2tOaNMXecAn",
        "outputId": "35f7d6eb-a38b-4186-99cb-fa96b976b5d9"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: sqlalchemy==1.3.9 in /usr/local/lib/python3.10/dist-packages (1.3.9)\n"
          ]
        }
      ],
      "source": [
        "!pip install sqlalchemy==1.3.9"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%load_ext sql"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "HlC0G-wehl64",
        "outputId": "6b33048c-31c9-4f24-b34b-103785ea129f"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "The sql extension is already loaded. To reload it, use:\n",
            "  %reload_ext sql\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import csv, sqlite3\n",
        "\n",
        "con = sqlite3.connect(\"my_data1.db\")\n",
        "cur = con.cursor()"
      ],
      "metadata": {
        "id": "CIx8zKCdhwzo"
      },
      "execution_count": 11,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "%sql ibm_db_sa://xcg80731:Z0Aq5Vwa8fZKzZ60@ba99a9e6-d59e-4883-8fc0-d6a8c9f7a08f.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud:"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "O_DkYjyOiPNT",
        "outputId": "10461343-9eda-4b5a-e78f-59acc1e0bd3d"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/connection.py\", line 45, in __init__\n",
            "    engine = sqlalchemy.create_engine(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/__init__.py\", line 479, in create_engine\n",
            "    return strategy.create(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/strategies.py\", line 54, in create\n",
            "    u = url.make_url(name_or_url)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py\", line 229, in make_url\n",
            "    return _parse_rfc1738_args(name_or_url)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py\", line 288, in _parse_rfc1738_args\n",
            "    return URL(name, **components)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py\", line 71, in __init__\n",
            "    self.port = int(port)\n",
            "ValueError: invalid literal for int() with base 10: ''\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 196, in execute\n",
            "    conn = sql.connection.Connection.set(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/connection.py\", line 70, in set\n",
            "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/connection.py\", line 45, in __init__\n",
            "    engine = sqlalchemy.create_engine(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/__init__.py\", line 479, in create_engine\n",
            "    return strategy.create(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/strategies.py\", line 54, in create\n",
            "    u = url.make_url(name_or_url)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py\", line 229, in make_url\n",
            "    return _parse_rfc1738_args(name_or_url)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py\", line 288, in _parse_rfc1738_args\n",
            "    return URL(name, **components)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/url.py\", line 71, in __init__\n",
            "    self.port = int(port)\n",
            "ValueError: invalid literal for int() with base 10: ''\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%sql SELECT TABSCHEMA, TABNAME, CREATE_TIME FROM SYSCAT.TABLES WHERE TABSCHEMA='XCG80731';"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "LgAf6TDailr8",
        "outputId": "0b1a589e-0c9d-45e6-bb2b-cc4cbe3ebf98"
      },
      "execution_count": 13,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT DISTINCT LAUNCH_SITE\n",
        "FROM SPACEXTBL;"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "SOVVjYIbiqJ-",
        "outputId": "4c7df660-ed00-4a83-c07c-02dec44f2456"
      },
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT COUNT(*) LAUNCH_SITE\n",
        "FROM SPACEXTBL\n",
        "WHERE LAUNCH_SITE = 'CCAFS LC-40';"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "NTnrQcH0itui",
        "outputId": "c2a393ef-efbc-4a4c-f32a-011db1c91337"
      },
      "execution_count": 15,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT COUNT(*) LAUNCH_SITE\n",
        "FROM SPACEXTBL\n",
        "WHERE LAUNCH_SITE = 'CCAFS SLC-40';"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "TXzglaLvjTXw",
        "outputId": "752f4a78-b6f0-43df-8b40-649f54581455"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT LAUNCH_SITE\n",
        "FROM SPACEXTBL\n",
        "WHERE LAUNCH_SITE LIKE 'CCA%'\n",
        "LIMIT 5;"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vnQkgZ2HjWo3",
        "outputId": "f5ade673-64ed-4bc1-e783-808cf4da8c7b"
      },
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT SUM(PAYLOAD_MASS__KG_)\n",
        "FROM SPACEXTBL\n",
        "WHERE Customer = 'NASA (CRS)';"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "AmLneHfHjZ1B",
        "outputId": "5dac1b99-3c06-45eb-8751-e8898c97483a"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT AVG(PAYLOAD_MASS__KG_)\n",
        "FROM SPACEXTBL\n",
        "WHERE Booster_Version LIKE 'F9 v1.0%';"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "76lGduhhjcnM",
        "outputId": "a21f7f19-bb0d-4068-eb25-3b2f7118beb5"
      },
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT MIN(Date)\n",
        "FROM SPACEXTBL\n",
        "WHERE Landing__Outcome = 'Success (ground pad)';"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "LRYF7bH1jfK8",
        "outputId": "2f93c843-a2d8-4289-c094-5ce4694d37c0"
      },
      "execution_count": 20,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT BOOSTER_VERSION\n",
        "FROM SPACEXTBL\n",
        "WHERE LANDING__OUTCOME = 'Success (drone ship)'\n",
        "    AND 4000 < PAYLOAD_MASS__KG_ < 6000;"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "oMmTC5zPjhmq",
        "outputId": "882110cf-baa4-4c45-b08f-f9c7f560269d"
      },
      "execution_count": 21,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT MISSION_OUTCOME, COUNT(MISSION_OUTCOME) AS TOTAL_NUMBER\n",
        "FROM SPACEXTBL\n",
        "GROUP BY MISSION_OUTCOME;"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "fp3s10FIjoBI",
        "outputId": "be558e23-1d98-4031-e833-97b1a79dfc3e"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT DISTINCT BOOSTER_VERSION\n",
        "FROM SPACEXTBL\n",
        "WHERE PAYLOAD_MASS__KG_ = (\n",
        "    SELECT MAX(PAYLOAD_MASS__KG_)\n",
        "    FROM SPACEXTBL);"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "JzCWoWvPjohl",
        "outputId": "da230176-33b5-4562-e1ac-cc920411ff87"
      },
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT LANDING__OUTCOME, BOOSTER_VERSION, LAUNCH_SITE\n",
        "FROM SPACEXTBL\n",
        "WHERE Landing__Outcome = 'Failure (drone ship)'\n",
        "    AND YEAR(DATE) = 2015;"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dvJTh3qKjsll",
        "outputId": "e042dd3b-cbf7-42ca-d826-223848da8d79"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%sql\n",
        "SELECT LANDING__OUTCOME, COUNT(LANDING__OUTCOME) AS TOTAL_NUMBER\n",
        "FROM SPACEXTBL\n",
        "WHERE DATE BETWEEN '2010-06-04' AND '2017-03-20'\n",
        "GROUP BY LANDING__OUTCOME\n",
        "ORDER BY TOTAL_NUMBER DESC"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "UZ4mp-_XjvZ4",
        "outputId": "2f89bccf-b024-4d52-c232-821d528aa9fd"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * sqlite:///my_data1.db\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/sql/magic.py\", line 203, in execute\n",
            "    conn.internal_connection.rollback()\n",
            "AttributeError: 'Connection' object has no attribute 'rollback'\n",
            "\n",
            "Connection info needed in SQLAlchemy format, example:\n",
            "               postgresql://username:password@hostname/dbname\n",
            "               or an existing connection: dict_keys(['sqlite:///my_data1.db'])\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "zOI0ILEBjye-"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}